Inventario/Inventario/Inventario.WebAdmin/Controllers/SalidasController.cs
using Inventario.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.WebAdmin.Controllers
{
    public class SalidasController : Controller
    {
        SalidasBL _salidasBL;
        SeccionesBL _seccionesBL;
        public SalidasController()
        {
            _salidasBL = new SalidasBL();
            _seccionesBL = new SeccionesBL();
        }

        // GET: Salidas
        public ActionResult Index()
        {
            var listadeSalidas = _salidasBL.ObtenerSalidas();

            return View(listadeSalidas);
        }

        public ActionResult Crear()
        {
            var nuevaSalida = new Salida();
            var secciones = _seccionesBL.ObtenerSecciones();

            ViewBag.SeccionID = new SelectList(secciones, "Id", "Nombre");

            return View(nuevaSalida);
        }

        [HttpPost]
        public ActionResult Crear(Salida salida)
        {
            if (ModelState.IsValid)
            {
                if (salida.SeccionID == 0)
                {
                    ModelState.AddModelError("SeccionID", "Seleccione una Seccion");
                    return View(salida);
                }

                _salidasBL.GuardarSalida(salida);
                return RedirectToAction("Index");
            }

            var secciones = _seccionesBL.ObtenerSecciones();

            ViewBag.SeccionesID = new SelectList(secciones, "Id", "Nombre");

            return View(salida);
        }

        public ActionResult Editar(int id)
        {
            var salida = _salidasBL.ObtenerSalida(id);
            var secciones = _seccionesBL.ObtenerSecciones();

            ViewBag.SeccionID = new SelectList(secciones, "ID", "Nombre", salida.SeccionID);
            return View(salida);
        }

        [HttpPost]
        public ActionResult Editar(Salida salida)
        {
            if (ModelState.IsValid)
            {
                if (salida.SeccionID == 0)
                {
                    ModelState.AddModelError("SeccionID", "Seleccione una seccion");
                        return View(salida);
                }

                _salidasBL.GuardarSalida(salida);

                return RedirectToAction("Index");
            }
            var secciones = _seccionesBL.ObtenerSecciones();

            ViewBag.SeccionID = new SelectList(secciones, "ID", "Nombre", salida.SeccionID);

            return View(salida);
        }

        public ActionResult Detalle(int id)
        {
            var salida = _salidasBL.ObtenerSalida(id);

            return View(salida);
        }
    }
}

Inventario/Inventario/Inventario.WebAdmin/Controllers/SalidasDetalleController.cs
using Inventario.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.WebAdmin.Controllers
{
    public class SalidaDetalleController : Controller
    {
        SalidasBL _salidaBL;
        ProductosBL _productosBL;

        public SalidaDetalleController()
        {
            _salidaBL = new SalidasBL();
            _productosBL = new ProductosBL();
        }

        // GET: SalidasDetalle
        public ActionResult Index(int id)
        {
            var salida= _salidaBL.ObtenerSalida(id);
            salida.ListadeSalidaDetalle = _salidaBL.ObtenerSalidaDetalle(id);

            return View(salida);
        }

        public ActionResult Crear(int id)
        {
            var nuevaSalidaDetalle = new SalidaDetalle();
            nuevaSalidaDetalle.SalidaID = id;

            var productos = _productosBL.ObtenerProductos();

            ViewBag.ProductoId = new SelectList(productos, "Id", "Descripcion");

            return View(nuevaSalidaDetalle);
        }

        [HttpPost]
        public ActionResult Crear(SalidaDetalle salidaDetalle)
        {
            if (ModelState.IsValid)
            {
                if (salidaDetalle.ProductoId == 0)
                {
                    ModelState.AddModelError("ProductoId", "Seleccione un producto");
                    return View(salidaDetalle);
                }

                _salidaBL.GuardarSalidaDetalle(salidaDetalle);
                return RedirectToAction("Index", new { id = salidaDetalle.SalidaID});
            }

            var productos = _productosBL.ObtenerProductos();
            ViewBag.ProductoId = new SelectList(productos, "Id", "Descripcion");

            return View(salidaDetalle);
        }

        public ActionResult Eliminar(int id)
        {
            var salidaDetalle = _salidaBL.ObtenerSalidaDetallePorId(id);

            return View(salidaDetalle);
        }

        [HttpPost]
        public ActionResult Eliminar(SalidaDetalle salidaDetalle)
        {
            _salidaBL.EliminarSalidaDetalle(salidaDetalle.Id);
            return RedirectToAction("Index", new { id = salidaDetalle.SalidaID });
        }
    }
}

Inventario/Inventario/Inventario.WebAdmin/Views/Salidas/Crear.cshtml
@model Inventario.BL.Salida

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salida</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SeccionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Total)
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index")
</div>

Inventario/Inventario/Inventario.WebAdmin/Views/Salidas/Detalle.cshtml
@model Inventario.BL.Salida

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Salida</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Seccion.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seccion.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.ID }) |
    @Html.ActionLink("Regresar a la Lista", "Index")
</p>

Inventario/Inventario/Inventario.WebAdmin/Views/Salidas/Editar.cshtml
@model Inventario.BL.Salida

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salida</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SeccionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Total)
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Inventario/Inventario/Inventario.WebAdmin/Views/Salidas/Index.cshtml
@model IEnumerable<Inventario.BL.Salida>

@{
    ViewBag.Title = "Salida";
}

<h2>Salida</h2>

<p>
    @Html.ActionLink("Nueva Salida", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Seccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Seccion.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.ID }) |
            @Html.ActionLink("Detalle", "Detalle", new { id=item.ID }) |
            @Html.ActionLink("Ver Productos", "Index",  "SalidaDetalle", new { id=item.ID }, null)
        </td>
    </tr>
}

</table>