Inventario/Inventario/Inventario.WebAdmin/Controllers/PedidosController.cs
using Inventario.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.WebAdmin.Controllers
{
    [Authorize]
    public class PedidosController : Controller
    {
        PedidosBL _pedidosBL;
        ProveedoresBL _proveedoresBL;

        public PedidosController()
        {
            _pedidosBL = new PedidosBL();
            _proveedoresBL = new ProveedoresBL();
        }

        // GET: Pedidos
        public ActionResult Index()
        {
            var listadePedidos = _pedidosBL.ObtenerPedidos();

            return View(listadePedidos);
        }

        public ActionResult Crear()
        {
            var nuevoPedido = new Pedido();
            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedorId = new SelectList(proveedores, "Id", "Nombre");

            return View(nuevoPedido);
        }

        [HttpPost]
        public ActionResult Crear(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                if (pedido.ProveedorId == 0)
                {
                    ModelState.AddModelError("ProveedorId", "Seleccione un proveedor");
                    return View(pedido);
                }

                _pedidosBL.GuardarPedido(pedido);

                return RedirectToAction("Index");
            }

            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedorId = new SelectList(proveedores, "Id", "Nombre");

            return View(pedido);
        }

        public ActionResult Editar(int id)
        {
            var pedido = _pedidosBL.ObtenerPedido(id);
            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedorId = new SelectList(proveedores, "Id", "Nombre", pedido.ProveedorId);


            return View(pedido);
        }

        [HttpPost]
        public ActionResult Editar(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                if(pedido.ProveedorId == 0)
                {
                    ModelState.AddModelError("ProveedorId", "Seleccione un proveedor");
                    return View(pedido);
                }

                _pedidosBL.GuardarPedido(pedido);

                return RedirectToAction("Index");
            }

            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedoresId = new SelectList(proveedores, "Id", "Nombre", pedido.ProveedorId);

            return View(pedido);
        }

        public ActionResult Detalle(int id)
        {
            var pedido = _pedidosBL.ObtenerPedido(id);

            return View(pedido);
        }
    }
}

Inventario/Inventario/Inventario.WebAdmin/Views/PedidoDetalle/Crear.cshtml
@model Inventario.BL.PedidoDetalle

@{
    ViewBag.Title = "Crear";
}

<h2>Crear producto para el pedido No. @Model.PedidoId</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PedidoDetalle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.PedidoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index", new { id = Model.PedidoId})
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Inventario/Inventario/Inventario.WebAdmin/Views/PedidoDetalle/Eliminar.cshtml
@model Inventario.BL.PedidoDetalle

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>&iquest;Esta seguro que desea eliminar este registro?</h3>
<div>
    <h4>PedidoDetalle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Pedido No.
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PedidoId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.PedidoId)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a la lista", "Index", new { id = Model.PedidoId })
        </div>
    }
</div>

Inventario/Inventario/Inventario.WebAdmin/Views/PedidoDetalle/Index.cshtml
@model Inventario.BL.Pedido

@{
    ViewBag.Title = "Orden Detalle";
}

<h2>Detalle de pedido No. @Model.Id</h2>



<table class="table table-bordered table-hover" >
    <tr>
        <td>Proveedor</td>
        <td>@Model.Proveedor.Nombre</td>
    </tr>
    <tr>
        <td>Telefono</td>
        <td>@Model.Proveedor.Telefono</td>
    </tr>
    <tr>
        <td>Direccion</td>
        <td>@Model.Proveedor.Direccion</td>
    </tr>
    <tr>
        <td>Fecha</td>
        <td>@Model.Fecha</td>
    </tr>
    <tr>
        <td>Total</td>
        <td>@Model.Total</td>
    </tr>
</table>


<p>
    @Html.ActionLink("Nuevo Producto", "Crear", new { id = Model.Id})
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            Producto
        </th>
        <th>
            Cantidad
        </th>
        <th>
            Precio
        </th>
        <th>
            Total
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.ListadePedidoDetalle) {
    <tr>
        <td>
            <img src="@item.Producto.UrlImagen" alt="@item.Producto.Descripcion" style="max-width: 64px; height: auto;"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Producto.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>

@Html.ActionLink("Regresar a pedidos", "Index", "Pedidos")