Inventario/Inventario/Inventario.WebAdmin/Controllers/ProductosController.cs
using Inventario.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.WebAdmin.Controllers
{
    [Authorize]
    public class ProductosController : Controller
    {
        ProductosBL _productosBL;
        CategoriasBL _categoriasBL;

        public ProductosController()
        {
            _productosBL = new ProductosBL();
            _categoriasBL = new CategoriasBL();

        }
        // GET: Productos
        public ActionResult Index()
        {
            var listadeProductos = _productosBL.ObtenerProductos();

            return View(listadeProductos);
        }


        public ActionResult Crear()
        {
            var nuevoProducto = new Producto();
            var categorias = _categoriasBL.ObtenerCategorias();
            ViewBag.CategoriaId = new SelectList(categorias, "Id", "Descripcion");


            return View(nuevoProducto);
        }

        [HttpPost]
        public ActionResult Crear(Producto producto, HttpPostedFileBase imagen)
        {
            if (ModelState.IsValid)
            {
                if (producto.CategoriaId == 0)
                {
                    ModelState.AddModelError("CategoriaId", "Seleccione una categoria primero porque no hay");
                    return View(producto);
                }
                if (imagen != null)
                {
                    producto.UrlImagen = GuardarImagen(imagen);
                }


                _productosBL.GuardarProducto(producto);
                return RedirectToAction("Index");

            }

            var categorias = _categoriasBL.ObtenerCategorias();
            ViewBag.CategoriaId = new SelectList(categorias, "Id", "Descripcion");
            return View(producto);


        }

        public ActionResult Editar(int id)
        {
            var producto = _productosBL.ObtenerProducto(id);
            var categorias = _categoriasBL.ObtenerCategorias();
            ViewBag.CategoriaId =
                new SelectList(categorias, "Id", "Descripcion", producto.CategoriaId);
            return View(producto);
        }

        [HttpPost]
        public ActionResult Editar(Producto producto)
        {
            if (ModelState.IsValid)
            {
                if (producto.CategoriaId == 0)
                {
                    ModelState.AddModelError("CategoriaId", "Seleccione una categoria primero porque no hay");
                    return View(producto);
                }



                _productosBL.GuardarProducto(producto);
                return RedirectToAction("Index");

            }

            var categorias = _categoriasBL.ObtenerCategorias();
            ViewBag.CategoriaId = new SelectList(categorias, "Id", "Descripcion");
            return View(producto);
        }

        public ActionResult Detalle(int id)
        {
            var producto = _productosBL.ObtenerProducto(id);


            return View(producto);
        }

        public ActionResult Eliminar(int id)
        {
            var producto = _productosBL.ObtenerProducto(id);
            var categorias = _categoriasBL.ObtenerCategorias();


            return View(producto);

        }

        [HttpPost]

        public ActionResult Eliminar(Producto producto)
        {
            _productosBL.EliminarProducto(producto.Id);
            return RedirectToAction("Index");
        }

        private string GuardarImagen(HttpPostedFileBase imagen)
        {
            string path = Server.MapPath("~/Imagenes/" + imagen.FileName);
            imagen.SaveAs(path);
            return "/Imagenes/" + imagen.FileName;
        }


    }
}

Inventario/Inventario/Inventario.WebAdmin/Views/Productos/Crear.cshtml
@model Inventario.BL.Producto

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm("Crear", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Seleccionar Imagen</label>

            <div class="col-md-10">
                <input type="file" name="imagen" id="imagen" />
            </div>
        </div>






        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "" } })
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("regresar", "Index")
</div>

Inventario/Inventario/Inventario.WebAdmin/Views/Productos/Detalle.cshtml
@model Inventario.BL.Producto

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </dt>
        <dd>
            <img src="@Model.UrlImagen" alt="@Model.Descripcion" style="width:200px; height:auto;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Regresar", "Index")
</p>

Inventario/Inventario/Inventario.WebAdmin/Views/Productos/Editar.cshtml
@model Inventario.BL.Producto

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Seleccionar Imagen</label>
            <div class="col-md-2">
                <input type="file" name="imagen" id="imagen" />
            </div>
            <div class="col-md-8">
                <img src="@Model.UrlImagen" alt="@Model.Descripcion" style="width:200px; height:auto;" />
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "" } })
                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
            </div>
        </div>







        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

Inventario/Inventario/Inventario.WebAdmin/Views/Productos/Eliminar.cshtml
@model Inventario.BL.Producto

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Esta seguro que desea eliminar esto?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </dt>
        <dd>
            <img src="@Model.UrlImagen" alt="@Model.Descripcion" style="width:200px; height:auto;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model.Activo)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

Inventario/Inventario/Inventario.WebAdmin/Views/Productos/Index.cshtml
@model IEnumerable<Inventario.BL.Producto>

@{
    ViewBag.Title = "Productos";
}

<h2>Productos</h2>

<p>
    @Html.ActionLink("Nuevo Producto", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <img src="@item.UrlImagen" alt="@item.Descripcion" style="width:64px; height:auto;" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalle", "Detalle", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
            </td>
        </tr>
    }

</table>