Inventario/Inventario/Inventario.WebAdmin/Controllers/PedidosController.cs
using Inventario.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.WebAdmin.Controllers
{
    [Authorize]
    public class PedidosController : Controller
    {
        PedidosBL _pedidosBL;
        ProveedoresBL _proveedoresBL;

        public PedidosController()
        {
            _pedidosBL = new PedidosBL();
            _proveedoresBL = new ProveedoresBL();
        }

        // GET: Pedidos
        public ActionResult Index()
        {
            var listadePedidos = _pedidosBL.ObtenerPedidos();

            return View(listadePedidos);
        }

        public ActionResult Crear()
        {
            var nuevoPedido = new Pedido();
            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedorId = new SelectList(proveedores, "Id", "Nombre");

            return View(nuevoPedido);
        }

        [HttpPost]
        public ActionResult Crear(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                if (pedido.ProveedorId == 0)
                {
                    ModelState.AddModelError("ProveedorId", "Seleccione un proveedor");
                    return View(pedido);
                }

                _pedidosBL.GuardarPedido(pedido);

                return RedirectToAction("Index");
            }

            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedorId = new SelectList(proveedores, "Id", "Nombre");

            return View(pedido);
        }

        public ActionResult Editar(int id)
        {
            var pedido = _pedidosBL.ObtenerPedido(id);
            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedorId = new SelectList(proveedores, "Id", "Nombre", pedido.ProveedorId);


            return View(pedido);
        }

        [HttpPost]
        public ActionResult Editar(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                if(pedido.ProveedorId == 0)
                {
                    ModelState.AddModelError("ProveedorId", "Seleccione un proveedor");
                    return View(pedido);
                }

                _pedidosBL.GuardarPedido(pedido);

                return RedirectToAction("Index");
            }

            var proveedores = _proveedoresBL.ObtenerProveedoresActivos();

            ViewBag.ProveedoresId = new SelectList(proveedores, "Id", "Nombre", pedido.ProveedorId);

            return View(pedido);
        }

        public ActionResult Detalle(int id)
        {
            var pedido = _pedidosBL.ObtenerPedido(id);

            return View(pedido);
        }
    }
}

Inventario/Inventario/Inventario.WebAdmin/Controllers/PedidosDetalleController.cs
using Inventario.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.WebAdmin.Controllers
{
    [Authorize]
    public class PedidoDetalleController : Controller
    {
        PedidosBL _pedidoBL;
        ProductosBL _productosBL;

        public PedidoDetalleController()
        {
            _pedidoBL = new PedidosBL();
            _productosBL = new ProductosBL();
        }

        // GET: PedidosDetalle
        public ActionResult Index(int id)
        {
            var pedido = _pedidoBL.ObtenerPedido(id);
            pedido.ListadePedidoDetalle = _pedidoBL.ObtenerPedidoDetalle(id);

            return View(pedido);
        }

        public ActionResult Crear(int id)
        {
            var nuevoPedidoDetalle = new PedidoDetalle();
            nuevoPedidoDetalle.PedidoId = id;

            var productos = _productosBL.ObtenerProductosActivos();
            ViewBag.ProductoId = new SelectList(productos, "Id", "Descripcion");

            return View(nuevoPedidoDetalle);
        }

        [HttpPost]
        public ActionResult Crear(PedidoDetalle pedidoDetalle)
        {
            if (ModelState.IsValid)
            {
                if (pedidoDetalle.ProductoId == 0)
                {
                    ModelState.AddModelError("ProductoId", "Seleccione un producto");
                    return View(pedidoDetalle);
                }

                _pedidoBL.GuardarPedidoDetalle(pedidoDetalle);
                return RedirectToAction("Index", new { id = pedidoDetalle.PedidoId });
            }

            var productos = _productosBL.ObtenerProductosActivos();
            ViewBag.ProductoId = new SelectList(productos, "Id", "Descripcion");

            return View(pedidoDetalle);
        }

        public ActionResult Eliminar(int id)
        {
            var pedidoDetalle = _pedidoBL.ObtenerPedidoDetallePorId(id);

            return View(pedidoDetalle);
        }

        [HttpPost]
        public ActionResult Eliminar(PedidoDetalle pedidoDetalle)
        {
            _pedidoBL.EliminarPedidoDetalle(pedidoDetalle.Id);

            return RedirectToAction("Index", new { id = pedidoDetalle.PedidoId });
        }
    }
}

Inventario/Inventario/Inventario.WebAdmin/Views/Pedidos/Crear.cshtml
@model Inventario.BL.Pedido

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Proveedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProveedorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProveedorId, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Total)
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Inventario/Inventario/Inventario.WebAdmin/Views/Pedidos/Detalle.cshtml
@model Inventario.BL.Pedido

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProveedorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProveedorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Regresar a la lista", "Index")
</p>

Inventario/Inventario/Inventario.WebAdmin/Views/Pedidos/Editar.cshtml
@model Inventario.BL.Pedido

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProveedorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProveedorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProveedorId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Total)
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Inventario/Inventario/Inventario.WebAdmin/Views/Pedidos/Index.cshtml
@model IEnumerable<Inventario.BL.Pedido>

@{
    ViewBag.Title = "Pedidos";
}

<h2>Pedidos</h2>

<p>
    @Html.ActionLink("Nuevo Pedido", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Proveedor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Proveedor.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalle", "Detalle", new { id=item.Id }) |
            @Html.ActionLink("Ver Productos", "Index", "PedidoDetalle", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>